services:
  init_db:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      sh -c "python -m scripts.populate_doctors_schedule &&
             python -m scripts.populate_hospital_faq &&
             python -m scripts.populate_hospital_locations &&
             python -m scripts.populate_appointment_process &&
             python -m scripts.populate_emergency_services"

  postgres:
    ports: [5432:5432]
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redisdata:/data

  app:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata:
  redisdata: