# .github/workflows/ci.yml

name: CI – Test & Build

# Trigger workflow ketika ada push atau pull request ke branch main/develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # 4) Jalankan unit & integration tests
      - name: Run pytest
        run: pytest --disable-warnings -q

      # 5) Build Docker image (verifikasi Dockerfile)
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag hospital-chatbot:ci
