# File: .github/workflows/ci.yml
name: CI – Build, Lint & Smoke Test

on:
  push:
    branches: [main]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # Lint with flake8 (opsional tapi direkomendasikan)
      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      # Build Docker image
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag hospital-chatbot:ci

      # Smoke-test: jalankan container & tes root endpoint
      - name: Run container and smoke test
        run: |
          docker run -d --name hc-test -p 8001:8000 hospital-chatbot:ci
          # tunggu container ready
          for i in {1..10}; do
            if curl -sSf http://localhost:8001/; then
              echo "🎉 API up"
              break
            fi
            echo "⏳ waiting for API..."
            sleep 2
          done
          docker stop hc-test
